### ISSUE TITLE
Python - Check palindrome using lambda

### ISSUE THREAD

**Issue by balamurugan1603** [balamurugan1603/Hacktoberfest-2021#5]
Given a string **X**. Check whether **X** is a palindrome or not using Lambda function in python. Print True if palindrome or False is not.

**Inputs :** 
racecar
hello

**Outputs :**
True
False

Add the working script to the repository.

**NOTE :**

- Change or add only the files which are relevant to the issue.
- Don't create spam pull requests.

**Comment by AravindHari** [comment]
Hey @balamurugan1603 can you assign me this task?

**Comment by AravindHari** [comment]
@balamurugan1603 is this repo not participating in HactoberFest?
