### ISSUE TITLE
Python - Symmetric difference

### ISSUE THREAD

**Issue by balamurugan1603** [balamurugan1603/Hacktoberfest-2021#8]
Given Two arrays X and Y. Find and print the symmetric difference between X and Y as an array.

**Inputs :**
1 2 3 4 5
2 3 4 5 6

**Output :**
[1, 6]

Add the working script to the repository.

**NOTE :**

- Change or add only the files which are relevant to the issue.
- Don't create spam pull requests.

**Comment by NarayanAdithya** [comment]
Plz assign me this issue.

**Comment by balamurugan1603** [comment]
@NarayanAdithya Sorry. This repo is only for first time contributors.
